name: Deploy MultiK8s
on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Service Key
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GKE_SA_KEY }}'
        
      - name: Set Project
        uses: google-github-actions/setup-gcloud@v0
        with: 
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Auth
        run: |-
          gcloud --quiet auth configure-docker
      
      - name: Get Credentials
        uses: google-github-actions/get-gke-credentials@v0
        with:
          cluster_name: multi-cluster
          location: us-central1-a

      - name: Apply
        run: |-
          kubectl apply -f k8s